export const READ_PRODUCTS = 'product/READ_PRODUCTS';
export const UPDATE_PRODUCT = 'product/UPDATE_PRODUCTS';
export const PRODUCT_WANTED_TO_UPDATE = 'product/PRODUCT_WANTED_TO_UPDATE';
export const SORT_PRODUCTS = 'product/SORT_PRODUCTS';
export const SHOW_SEARCH_SUGGESTIONS = 'products/SHOW_SEARCH_SUGGESTIONS';
export const SEARCH_PRODUCTS = 'product/SEARCH_PRODUCTS';
export const CLEAR_SEARCH_INPUT_FIELD = 'product/CLEAR_SEARCH_INPUT_FIELD';
export const CLEAR_SEARCH_RESULTS = 'product/CLEAR_SEARCH_RESULTS';
